server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api_restful_mysql_database?useTimezone=true&serverTimezone=UTC
    username: admin123
    password: admin123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

spring-doc:
  pathsToMatch:
    - /auth/**
    - /**/v1/**
  swagger-ui:
    use-root-path: true

cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://yuri.studies.com.br

security:
  jwt:
    token:
      secret-key: "secret-key"
      expire-length: 3600000

file:
  upload-dir: /UploadDir