server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: restful-spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/api-restful?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

spring-doc:
  pathsToMatch: /**
  swagger-ui:
    use-root-path: true

cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://yuri.studies.com.br